### ISSUE TITLE
Endpoint `v1/datasets` not always returns all available datasets (missing `klima-v1-10min`)

### ISSUE THREAD

**Issue by retostauffer** [Geosphere-Austria/dataset-api-docs#11]
Dear all

**Context:** I am calling [`/v1/datasets?type=station`](https://dataset.api.hub.geosphere.at/v1/datasets?type=station) to get all available station datasets/API endpoints.

**Problem:** The API does not always return the same data sets, to be more precise the dataset `klima-v1-10min` seems to be included only half of the time.

**Replicate the problem:** It can be seen in the browser when refreshing [the page](https://dataset.api.hub.geosphere.at/v1/datasets?type=station) a few times. To make it more reproducible I've written a small python script which calls the API 20 times and checks the datasets returned.

* Script (github gist) can be found here: https://gist.github.com/retostauffer/940a0bda101d2b25aa907f741773f73b

The output below shows the script calling the API 20 times. Half of the time the returned JSON object contains 8 datasets, half of the time 7 missing `klima-v1-10min`.

```
[...]

Overall counts:
    20  /station/historical/histalp-v1-1y
    20  /station/historical/klima-v1-1d
    20  /station/historical/klima-v1-1h
    20  /station/historical/klima-v1-1m
    20  /station/historical/tawes-v1-10min
    20  /station/current/tawes-v1-10min
    20  /station/historical/synop-v1-1h
    10  /station/historical/klima-v1-10min
```

As far as I can see this seems to be random (50% chance that `klima-v1-10min` is included or not).

All best (and thanks for the API!!)

**Comment by dlang-geosphereat** [comment]
Hi @retostauffer ,

thanks for your feedback. We are currently experiencing problems with the data source, that provides the data for `klima-v1-10min` (which is also why the available data is not up to date).  This means:
* data is currently not updated
* new connections to the data store cannot be made.
* datasets other than `klima-v1-10min` should not be affected.

The effect you observed is a load balancing issue: Some replicas of our service can query the data, some can't (because new connections cannot be made, see above). There is nothing wrong with your query.

We are working to resolve this issue.

**Comment by retostauffer** [comment]
Hi @dlang-geosphereat

thanks for the fast reply and the detailed explanation. In this case this issue is obsolete and can be closed (please feel free to do so). Good luck resolving the issue and all the best from Innsbruck!

**Comment by dlang-geosphereat** [comment]
This issue has been fixed.
