### ISSUE TITLE
Timeout querying Spartacus for larger areas

### ISSUE THREAD

**Issue by febsn** [Geosphere-Austria/dataset-api-docs#12]
I always get `504 Gateway Timeout` errors ("Kong Error, the upstream server is timing out") when querying larger areas for `spartacus-v2-1m-1km` data. I'm trying to get precipitation data for Lower Austria, but even if I increase `spatial_resolution_m` to 10000 or even 100000 the connection times out.

An example query I'm using is https://dataset.api.hub.geosphere.at/v1/grid/historical/spartacus-v2-1m-1km?parameters=RR&start=2021-01-01T00%3A00&end=2021-01-01T00%3A00&bbox=47.40%2C14.41%2C49.02%2C17.08&output_format=geojson&spatial_resolution_m=10000

Am I making a mistake in querying, or is the API not prepared for areas of that size? I couldn't find any constraints in the docs.
Please let me know if I can provide further information.

**Comment by afuchs-geosphereat** [comment]
Your requests looks fine and is well within [the request size limit](https://dataset.api.hub.geosphere.at/v1/docs/user-guide/request_size_limit.html).

Instead it seems the timeout is caused by a bug when creating the geojson output. We will look into it. Thanks for bringing this to our attention.

In the meantime, if this is an option for you, you can use `output_format=netcdf`, which seems to work fine.

**Comment by febsn** [comment]
Thank you very much for your response! I'll wait for further updates, please let me know if I can contribute anything.

**Comment by afuchs-geosphereat** [comment]
Hello @febsn,
We have deployed a fix today. The above query should not cause a timeout anymore.
Best regards
