### ISSUE TITLE
Internal server error when fetching data outside of provided range

### ISSUE THREAD

**Issue by loiss01** [Geosphere-Austria/dataset-api-docs#27]
Hello,

I've encountered an issue when querying data from the API with a time range that exceeds the acceptable boundaries. Instead of receiving a meaningful error message or a more graceful handling of the request, the API returns an Internal Server Error.

**Steps to Reproduce:**

- Make a GET request to the API endpoint, providing a time range that exceeds the acceptable boundaries for that station.

For example, using the following request:

https://dataset.api.hub.geosphere.at/v1/station/historical/klima-v2-1h?parameters=rr&start=2020-01-01T00%3A00%3A00.000Z&end=2024-01-31T00%3A00%3A00.000Z&station_ids=114&output_format=csv&filename=Messstationen+Stundendaten+v2+Datensatz_20200101T0000_20240131T0000

The data range provided by the station is only from 01.09.1955 to 01.01.1986. It took me around two hours to realize that the issue was due to the absence of data within my requested time range.

**Expected Behavior:**
The API should return a meaningful error message indicating that the provided time range is out of bounds or handle the request more gracefully, such as returning a relevant HTTP status code (e.g., 400 Bad Request) along with a descriptive error message.

**Actual Behavior:**
The API responds with an Internal Server Error (HTTP 500) without providing any indication as to why the error occurred or how to resolve it.

Enhancing the API with informative error messages or more graceful handling of such requests would significantly improve its usability and developer experience.

Thank you for your time and consideration in reviewing this issue. Your attention to improving the API's functionality is greatly appreciated.

~Alois

**Comment by afuchs-geosphereat** [comment]
Hello Alois,

thank you for your feedback! I am sorry for the lost time this error caused you.

In this case the API should return an array with `none` values, see for example the [klima_v1 behavior](https://dataset.api.hub.geosphere.at/v1/station/historical/klima-v1-1h?parameters=RSX&start=2024-01-01&end=2024-01-02&station_ids=11700&output_format=geojson).

This may not be ideal feedback wise but allows much simpler handling of scenarios where only some of the stations do not have data for the requested parameter in the request time range.

A fix for this bug is in the working and we will let you know when the fix is deployed.

Best regards
Andreas

**Comment by afuchs-geosphereat** [comment]
The fix is now deployed. Requesting data outside a stations valid time should no longer cause an internal server error.
