### ISSUE TITLE
Undocumented behavior when requesting a timeseries outside of the bounding box of a data set

### ISSUE THREAD

**Issue by kosmoz** [Geosphere-Austria/dataset-api-docs#31]
Hi,

when trying out the forecast API, we noticed some strange behavior when requesting data for a location outside of the bounding box for a data set. It seems like data is returned, but for a different location, which may not be inside the bounding box either. 

Example:
https://dataset.api.hub.geosphere.at/v1/timeseries/forecast/nwp-v1-1h-2500m?parameters=sy&lat_lon=-23.5478%2C-46.6551 returns data for 5.498,42.981 (which is in Somalia)

I understand that this is definitely a user error, but I think the API should validate the bounding box, or at least the behavior if they are not should be documented.

**Comment by dlang-geosphereat** [comment]
Hi @kosmoz , thanks for bringing the problem to our attention.

The API should:
* provide a small border (0,5x of the spatial resolution), in which requests are out of bounds, but allowed. This is, because in many cases data is originally on some grid and projected to WGS84, which means that we do not necessarily have data on the edges of the bbox. This information is encoded in the metadata as `bbox_outer`. (https://dataset.api.hub.geosphere.at/v1/timeseries/forecast/nwp-v1-1h-2500m/metadata)
* reject requests that are outside of this outer bounding box (e.g. your request).

In this case, I see two problems on our side:
1. `bbox_outer` is incorrectly set (ranges from approx. -1200 to 1200). This means our validation layer never rejects requests, except ones that are even out of this abnormally large range, e.g: https://dataset.api.hub.geosphere.at/v1/timeseries/forecast/nwp-v1-1h-2500m?parameters=sy&lat_lon=-2003.5478%2C-46.6551
2. The wrong data is returned. When data access is performed, we look for the nearest grid point and return its data. The nearest point in your case would be ` 42.981,5.498` (Latitude, Longitude), which would be Marseille, France. However, you get ` 5.498, 42.981` (Latitude, Longitude), which is in Africa. It looks to me, that somehow in our data store lat/lon are getting mixed up.

I'll clarify these issues with our data producers.

**Comment by dlang-geosphereat** [comment]
Fix for `bbox_outer` is finally deployed and https://dataset.api.hub.geosphere.at/v1/timeseries/forecast/nwp-v1-1h-2500m/metadata now shows correctly, not only where data points exist (`bbox`), but also where queries are allowed (`bbox_outer`).

As for lat/lon, as already mentioned this is a usage problem and will be tackled in the future.
