### ISSUE TITLE
Inconsistent coupling of timestamps and data for Graz-Uni (ID 30)

### ISSUE THREAD

**Issue by michelesalmi** [Geosphere-Austria/dataset-api-docs#37]
Hi,

since the displacement of the station in Graz-Universität (ID 30) something does not work as expected in the API as the data array is always longer than the timestamps array (and filled with NaNs, probably one per day, but unequally distributed along the array).

Am I missing something or is there something wrong on the API side since the old station and the new station have been merged? All other stations work mostly fine.

For your reference plese see this example for "tlmax" in the last week with 7 timestamps and 14 data values (7 wrongly appended NaNs and 1 correct NaN for today as I am speaking that will be filled with a value in the next few hours): https://dataset.api.hub.geosphere.at/v1/station/historical/klima-v2-1d?parameters=tlmax&station_ids=30&start=2024-08-01&end=2024-08-07

Thank you for your help,
Michele

**Comment by dlang-geosphereat** [comment]
Hi Michele!

Thank you for reporting this error. The problem is that the station series "30" has two active stations:
![image](https://github.com/user-attachments/assets/23f460ae-9bfa-460a-98d0-f743395c0507)

Both stations, 16412 and 16414 have their end date set to "2100", which means they both provide data for station series 30, resulting in twice as many data points as time steps. This obviously should not be, and I forwarded this problem internally.

Meanwhile, as a workaround, you can just use the newer station (16414) directly: https://dataset.api.hub.geosphere.at/v1/station/historical/klima-v2-1d?parameters=tlmax&station_ids=16414&start=2024-08-01&end=2024-08-07

**Comment by michelesalmi** [comment]
Thank you for the quick reply! :)

Will this fix get rid of the NaNs already present in the database for the past months?

I am asking this because the station in Jenbach (I think ID 43 if I remember correctly) had the same issue sometime in the past and the NaNs are still preventing a smooth download of the whole timeserie even if at the moment the new values are stored correctly.

Thanks again and have a great day.
Michele

**Comment by michelesalmi** [comment]
Wonderful thank you! Let us know as soon as you fixed it! I am rather sure that there are no further stations with the same issue (at least for the ones currently active) as I have a small script running that is doing exactly this check. Thank you again and have a nice evening.

**Comment by dlang-geosphereat** [comment]
We just updated the two offending station series (30 and 42). This resolves this issue.

Thank you for reporting this problem!
